jwt:
  # Keycloak realm public key
  public-key: ${SSO_PUBLIC_KEY}

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SSO_AUTH_SERVER_URL}/realms/${SSO_REALM}
          jwk-set-uri: ${SSO_AUTH_SERVER_URL}/realms/${SSO_REALM}/protocol/openid-connect/certs
